### ISSUE TITLE
Investigate codecov posibilities

### ISSUE THREAD

**Issue by kowalczyka** [servicecatalog/oscm-app-api#13]

**Comment by Crystalzord** [comment]
I investigated CodeCov and implemented it into the CI process of oscm-cm-api module already. The implementation consists of four steps:
1. Apply JaCoCo plugin in build.gradle file and configure it to generate xml reports.
2. Add .codecov.yml with configuration for CodeCov to add comments to pull requests.
3. Modify .travis.yml to send the reports to CodeCov after successful build.
4. Modify README file to display CodeCov badge with current coverage.
See: https://github.com/servicecatalog/oscm-cm-api/commit/5fcf4c9866bc6f212b2c538fe9abaad6aea4dc03

Also I created a test pull request (don't merge - just for test purpose!) to show how CodeCov  can automatically comment pull requests with coverage status difference that will occur if the pull request would be merged.
See: https://github.com/servicecatalog/oscm-cm-api/pull/12

Please verify and approve eventually so I can implement it on other modules.
Best regards
Lukasz
